# Generated by Django 6.0.2 on 2026-02-26 05:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код формы')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
            },
        ),
        migrations.CreateModel(
            name='KnownChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='ID чата')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('chat_type', models.CharField(choices=[('group', 'Группа'), ('supergroup', 'Супергруппа')], max_length=20, verbose_name='Тип чата')),
                ('is_active', models.BooleanField(default=True, verbose_name='Бот в чате')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность')),
            ],
            options={
                'verbose_name': 'Известный чат',
                'verbose_name_plural': 'Известные чаты',
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.BigIntegerField(unique=True, verbose_name='ID в Telegram')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Полное имя')),
                ('role', models.CharField(choices=[('developer', 'Разработчик'), ('admin', 'Администратор'), ('filler', 'Заполнитель')], default='filler', max_length=20, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
            },
        ),
        migrations.CreateModel(
            name='OrgObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('passport_json', models.JSONField(blank=True, default=dict, verbose_name='Паспорт (JSON)')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('closed', 'Закрыт')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('chat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_object', to='core.knownchat', verbose_name='Привязанный чат')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Номер/название скважины')),
                ('planned_depth_m', models.FloatField(blank=True, null=True, verbose_name='Плановая глубина (м)')),
                ('current_depth_m', models.FloatField(blank=True, null=True, verbose_name='Текущая глубина (м)')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('closing_pending', 'Ожидает подтверждения закрытия'), ('closed', 'Закрыта')], default='active', max_length=30, verbose_name='Статус')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='core.orgobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Скважина',
                'verbose_name_plural': 'Скважины',
                'ordering': ['object', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата отчёта')),
                ('payload_json', models.JSONField(blank=True, default=dict, verbose_name='Данные полей')),
                ('message_text', models.TextField(blank=True, verbose_name='Текст сообщения')),
                ('tg_chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID чата отправки')),
                ('tg_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID сообщения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.orgobject', verbose_name='Объект')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tguser', verbose_name='Автор')),
                ('well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CloseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.orgobject', verbose_name='Объект')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_requests', to='core.report', verbose_name='Отчёт')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_close_requests', to='core.tguser', verbose_name='Кто решил')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_close_requests', to='core.tguser', verbose_name='Инициатор')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'Запрос на закрытие',
                'verbose_name_plural': 'Запросы на закрытие',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Ключ поля (латиница)')),
                ('label', models.CharField(max_length=255, verbose_name='Название поля')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('checkbox', 'Флаг'), ('select', 'Список')], max_length=20, verbose_name='Тип поля')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательное')),
                ('options_json', models.JSONField(blank=True, default=list, verbose_name='Варианты (для списка)')),
                ('order_index', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.form', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Поле формы',
                'verbose_name_plural': 'Поля формы',
                'ordering': ('order_index', 'id'),
                'unique_together': {('form', 'key')},
            },
        ),
    ]
