# Generated by Django 6.0.2 on 2026-02-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgobject',
            name='object_type',
            field=models.CharField(choices=[('private', 'Частный'), ('federal', 'Федеральный')], default='private', max_length=20, verbose_name='Тип объекта'),
        ),
        migrations.AddField(
            model_name='well',
            name='liquidation_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата ликвидации'),
        ),
        migrations.AddField(
            model_name='well',
            name='maintenance_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершение сопровождения'),
        ),
        migrations.AddField(
            model_name='well',
            name='maintenance_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало сопровождения'),
        ),
        migrations.AddField(
            model_name='well',
            name='planned_pumping_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='Плановая длительность ОФР (часы)'),
        ),
        migrations.AddField(
            model_name='well',
            name='pumping_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершение ОФР'),
        ),
        migrations.AddField(
            model_name='well',
            name='pumping_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало ОФР'),
        ),
        migrations.AddField(
            model_name='well',
            name='stage',
            field=models.CharField(choices=[('drilling', 'Бурение'), ('pumping', 'ОФР'), ('maintenance', 'Сопровождение'), ('liquidation', 'Ликвидация'), ('completed', 'Завершена')], default='drilling', max_length=20, verbose_name='Этап'),
        ),
    ]
