# Generated by Django 6.0.2 on 2026-02-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orgobject_object_type_well_liquidation_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='stage',
            field=models.CharField(blank=True, choices=[('drilling', 'Бурение'), ('pumping', 'ОФР'), ('maintenance', 'Сопровождение'), ('liquidation', 'Ликвидация'), ('completed', 'Завершена'), ('force_majeure', 'Форс-мажор')], max_length=20, null=True, verbose_name='Этап отчёта'),
        ),
        migrations.AddField(
            model_name='well',
            name='total_pumping_hours',
            field=models.FloatField(default=0.0, verbose_name='Накоплено часов ОФР'),
        ),
        migrations.AlterField(
            model_name='well',
            name='stage',
            field=models.CharField(choices=[('drilling', 'Бурение'), ('pumping', 'ОФР'), ('maintenance', 'Сопровождение'), ('liquidation', 'Ликвидация'), ('completed', 'Завершена'), ('force_majeure', 'Форс-мажор')], default='drilling', max_length=20, verbose_name='Текущий этап'),
        ),
    ]
