# Generated by Django 6.0.2 on 2026-02-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_report_stage_well_total_pumping_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='maintenance_needed',
            field=models.BooleanField(default=False, verbose_name='Требуется сопровождение'),
        ),
        migrations.AddField(
            model_name='well',
            name='previous_stage',
            field=models.CharField(blank=True, choices=[('drilling', 'Бурение'), ('pumping', 'ОФР'), ('maintenance', 'Сопровождение'), ('liquidation', 'Ликвидация'), ('completed', 'Завершена'), ('force_majeure', 'Форс-мажор')], max_length=20, null=True, verbose_name='Предыдущий этап (для форс-мажора)'),
        ),
    ]
