# Generated by Django 6.0.2 on 2026-02-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_well_maintenance_needed_well_previous_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='maintenance_completed_at',
        ),
        migrations.RemoveField(
            model_name='well',
            name='maintenance_started_at',
        ),
        migrations.AddField(
            model_name='well',
            name='closed_reason',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Причина закрытия'),
        ),
        migrations.AddField(
            model_name='well',
            name='mode_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершение режима'),
        ),
        migrations.AddField(
            model_name='well',
            name='mode_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало режима'),
        ),
        migrations.AddField(
            model_name='well',
            name='planned_mode_count',
            field=models.IntegerField(default=0, verbose_name='Плановое количество режимов'),
        ),
        migrations.AddField(
            model_name='well',
            name='remaining_mode_count',
            field=models.IntegerField(default=0, verbose_name='Осталось режимов'),
        ),
        migrations.AddField(
            model_name='well',
            name='total_drilling_pumping_hours',
            field=models.FloatField(default=0.0, verbose_name='Часы прокачки при бурении'),
        ),
        migrations.AlterField(
            model_name='report',
            name='stage',
            field=models.CharField(blank=True, choices=[('drilling', 'Бурение'), ('pumping', 'ОФР'), ('mode', 'Режим'), ('liquidation', 'Ликвидация'), ('completed', 'Завершена')], max_length=20, null=True, verbose_name='Этап отчёта'),
        ),
        migrations.AlterField(
            model_name='well',
            name='previous_stage',
            field=models.CharField(blank=True, choices=[('drilling', 'Бурение'), ('pumping', 'ОФР'), ('mode', 'Режим'), ('liquidation', 'Ликвидация'), ('completed', 'Завершена')], max_length=20, null=True, verbose_name='Предыдущий этап (для форс-мажора)'),
        ),
        migrations.AlterField(
            model_name='well',
            name='stage',
            field=models.CharField(choices=[('drilling', 'Бурение'), ('pumping', 'ОФР'), ('mode', 'Режим'), ('liquidation', 'Ликвидация'), ('completed', 'Завершена')], default='drilling', max_length=20, verbose_name='Текущий этап'),
        ),
    ]
