# Generated by Django 6.0.2 on 2026-02-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_well_maintenance_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='maintenance_needed',
        ),
        migrations.AddField(
            model_name='well',
            name='total_discharge_hours',
            field=models.FloatField(default=0.0, verbose_name='Накоплено часов откачки'),
        ),
    ]
