# Generated by Django 6.0.2 on 2026-03-02 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_well_maintenance_needed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgobject',
            name='object_type',
        ),
    ]
